# Generated by Django 4.1.5 on 2023-01-16 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nazwa')),
                ('city', models.CharField(max_length=64, verbose_name='Miasto')),
                ('contact', models.CharField(max_length=64, verbose_name='Kontakt')),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Imię')),
                ('surname', models.CharField(max_length=32, verbose_name='Nazwisko')),
                ('phone', models.IntegerField(blank=True, max_length=9, verbose_name='Nr telefonu')),
                ('company', models.CharField(max_length=32, verbose_name='Firma')),
            ],
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr', models.FloatField(max_length=16, verbose_name='Nr ewidencyjny')),
                ('type', models.CharField(max_length=128, verbose_name='Typ')),
                ('producer', models.CharField(max_length=64, verbose_name='Marka')),
                ('capacity', models.CharField(blank=True, max_length=32, verbose_name='Pojemność')),
                ('size', models.CharField(blank=True, max_length=32, verbose_name='Wielkość')),
                ('date', models.DateField(blank=True, verbose_name='Data pobrania')),
                ('construction', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='storage_5d_pr.construction', verbose_name='Obiekt')),
                ('workers', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='storage_5d_pr.workers', verbose_name='Pracownik')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('construction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage_5d_pr.construction', verbose_name='Obiekt')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage_5d_pr.tools', verbose_name='Narzędzie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
                ('workers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage_5d_pr.workers', verbose_name='Pracownik')),
            ],
        ),
    ]
