# Generated by Django 4.1.5 on 2023-01-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_5d_pr', '0002_alter_workers_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nr telefonu'),
        ),
    ]
