# Generated by Django 4.1.5 on 2023-01-17 12:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage_5d_pr', '0003_alter_workers_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workers',
            options={'ordering': ['surname']},
        ),
        migrations.AlterField(
            model_name='tools',
            name='construction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage_5d_pr.construction', verbose_name='Obiekt'),
        ),
        migrations.AlterField(
            model_name='tools',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Data pobrania'),
        ),
        migrations.AlterField(
            model_name='tools',
            name='workers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage_5d_pr.workers', verbose_name='Pracownik'),
        ),
    ]
