# Generated by Django 4.1.5 on 2023-01-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_5d_pr', '0006_alter_tools_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='construction',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='history',
            name='comment',
            field=models.TextField(blank=True, max_length=164, verbose_name='Komentarz'),
        ),
        migrations.AddField(
            model_name='tools',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workers',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
