# Generated by Django 4.1.5 on 2023-01-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_5d_pr', '0007_construction_deleted_history_comment_tools_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='construction',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='tools',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='workers',
            name='deleted',
        ),
        migrations.AddField(
            model_name='workers',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktywny'),
        ),
    ]
