# Generated by Django 4.1.5 on 2023-01-17 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage_5d_pr', '0009_remove_history_tool_history_tool_nr_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-date']},
        ),
    ]
