# Generated by Django 4.1.5 on 2023-01-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_5d_pr', '0010_alter_history_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='construction',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Obiekt'),
        ),
        migrations.AlterField(
            model_name='history',
            name='workers',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Pracownik'),
        ),
    ]
