# Generated by Django 4.1.5 on 2023-01-17 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage_5d_pr', '0012_alter_history_options_alter_history_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-creation_date']},
        ),
        migrations.RenameField(
            model_name='history',
            old_name='date',
            new_name='creation_date',
        ),
    ]
