# Generated by Django 4.1.5 on 2023-01-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_5d_pr', '0013_alter_history_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='tool_nr',
            field=models.FloatField(default=0.0, max_length=32, verbose_name='Nr ew'),
        ),
    ]
