# Generated by Django 4.1.5 on 2023-01-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_5d_pr', '0015_history_tool_date_alter_history_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data_wpisu'),
        ),
    ]
