# Generated by Django 4.1.5 on 2023-01-18 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_5d_pr', '0016_alter_history_creation_date'),
    ]
