# Generated by Django 4.1.5 on 2023-01-18 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage_5d_pr', '0018_alter_history_tool_date'),
    ]


