# Generated by Django 4.1.5 on 2023-01-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_5d_pr', '0019_remove_history_tool_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='tool_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
    ]
