# Generated by Django 4.1.5 on 2023-01-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_5d_pr', '0020_history_tool_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='tool_nr',
            field=models.FloatField(default=0.0, max_length=32, null=True, verbose_name='Nr ew'),
        ),
        migrations.AlterField(
            model_name='history',
            name='tool_producer',
            field=models.CharField(default=0, max_length=64, null=True, verbose_name='Marka'),
        ),
        migrations.AlterField(
            model_name='history',
            name='tool_type',
            field=models.CharField(default=0, max_length=128, null=True, verbose_name='Typ'),
        ),
    ]
