# Generated by Django 4.1.5 on 2023-01-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_5d_pr', '0022_alter_tools_nr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='tool_nr',
            field=models.CharField(default=0.0, max_length=32, null=True, verbose_name='Nr ew'),
        ),
    ]
